export const LOGIN_USER = "[User] - login user";
export const LOGOUT_USER = "[User] - log out user";
export const REGISTER_USER = "[User] - register user";
export const GET_USER = "[User] - get user info";
export const RESET_PASSWORD = "[USER] - reset password";
export const UPDATE_DIALOG = "[Dialog] - update open and content";
export const GET_ALL_PERMISSIONS = "[Permissions] - get all permissions";
export const GET_ROLES = "[User Management] - get role info";
export const GET_LIST_USERS = "[User Management] - get user list";
export const UPDATE_FILTER_LIST = "[User Management] - update role filter";
export const SET_OTHER_USER = "[User Management] - get other user information";
export const UPDATE_USER_ROLES =
  "[User Management] - set other user role information";
export const GET_INDIV_TABLE = "[Inventory] - get individual table";
export const GET_ALL_FILES = "[Files] - get all files";
export const OPEN_FILE = "[Files] - open specific file";
export const GET_TABLE_LIST = "[Inventory] - get list of tables";
export const GET_ALL_EVENTS =  "[Events] - get list of events";
export const GET_EVENT =  "[Events] - get specific events";